name: Build Images

on:
  workflow_call:
    inputs:
      runner-os:
        description: Operating system ("ubuntu-22.04")
        type: string
        required: true
      platform:
        description: Platform i.e. "linux/amd64", "linux/arm64"
        type: string
        required: true
      cache-key:
        description: Cache key
        type: string
        required: true
      cache-restore-keys:
        description: Cache restore keys list
        type: string
        required: true

jobs:
  build:
    name: Build Image
    runs-on: ${{ inputs.runner-os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          platform=${{ inputs.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ inputs.cache-key }}
          restore-keys: ${{ inputs.cache-restore-keys }}
      - name: Image name
        id: image_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ inputs.platform }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image_name.outputs.lowercase }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.actor != 'dependabot[bot]' }}
          context: .
          platforms: ${{ inputs.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ steps.image_name.outputs.lowercase }},push-by-digest=true,name-canonical=true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
        # Temp fix?
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
