name: Main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: Ilyes512/github-actions/.github/workflows/build.yml@0.1.0
    strategy:
      fail-fast: false
      matrix:
        platform: ['linux/amd64', 'linux/arm64']
        os: ['ubuntu-22.04']
    with:
      runner-os: ${{ matrix.os }}
      platform: ${{ matrix.platform }}
      cache-key: ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ github.ref_name }}-${{ github.sha }}
      cache-restore-keys: |
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ github.ref_name }}-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-

  merge:
    uses: Ilyes512/github-actions/.github/workflows/merge.yml@0.1.0
    with:
      runner-os: ubuntu-22.04
