name: Merge images to manifest

on:
  workflow_call:
    inputs:
      runner-os:
        description: Operating system ("ubuntu-22.04")
        type: string
        required: true

jobs:
  merge:
    name: Merge Image
    runs-on: ${{ inputs.runner-os }}
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
      - name: Image name
        id: image_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image_name.outputs.lowercase }}
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ steps.image_name.outputs.lowercase }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ steps.image_name.outputs.lowercase }}:${{ steps.meta.outputs.version }}

