name: Pull Requests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: Ilyes512/github-actions/.github/workflows/build.yml@php-workflows
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    with:
      runner-os: ubuntu-22.04
      platform: ${{ matrix.platform }}
      image-name: ghcr.io/${{ github.repository }}
      cache-key: ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-${{ github.event.number }}-${{ github.sha }}
      cache-restore-keys: |
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-${{ github.event.number }}-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-main-

  merge:
    uses: Ilyes512/github-actions/.github/workflows/merge.yml@php-workflows
    needs: build
    with:
      image-name: ghcr.io/${{ github.repository }}
      runner-os: ubuntu-22.04
