name: Tags

on:
  push:
    tags: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: Ilyes512/github-actions/.github/workflows/build.yml@php-workflows
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    with:
      runner-os: ubuntu-22.04
      platform: ${{ matrix.platform }}
      cache-key: ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ github.ref_name }}-${{ github.sha }}
      cache-restore-keys: |
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ github.ref_name }}-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-main-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-

  merge:
    uses: Ilyes512/github-actions/.github/workflows/merge.yml@php-workflows
    needs: build
    with:
      image-name: ghcr.io/${{ github.repository }}
      runner-os: ubuntu-22.04
